# On Chance

FROM node:16.14-alpine

WORKDIR /onchance

COPY . .

CMD ["npm", "run", "server:dev-remote-mongo-local-docker"]

# WORKDIR /onchance
# COPY . .

# # FOR DEBUG SERVR ONLY
# RUN npm install
# RUN npm run production

# CMD ["npm", "run", "start-nodemon"]

EXPOSE 3000
