# On Chance

FROM node:14.7.0

WORKDIR /onchance

COPY . .

CMD ["npm", "run", "server:dev-local-docker"]

WORKDIR /onchance
COPY . .

# # FOR DEBUG SERVR ONLY
# RUN npm install
# RUN npm run production

# CMD ["npm", "run", "start-nodemon"]

EXPOSE 3000
